#!/usr/bin/env python3
# V80 (APP: SwiftAngle). With V79 the ANGLE/SwiftShader driver loads, Unity creates a GLES 3.0 context and the
# shaders compile, but SIGSEGV in rr::Routine::bind() (LRUCache::add with a null routine) from
# VertexProcessor::routine: LLVMReactorJIT::acquireRoutine returns nullptr when linking the JIT
# code fails (symbol.getAddress() with error) and the error is discarded ("TODO: Log the symbol resolution
# errors"). The external resolver only knows floorf/nearbyintf/truncf; on ARM32 the code generated by
# LLVM llama a rutinas EABI (__aeabi_idiv, __aeabi_uidivmod, __aeabi_l2f, memcpy, __aeabi_unwind_cpp_pr0,
# __sync_synchronize...). The patch:
#  1) logs (liblog, tag SwiftShader) the unresolved symbol and the link error;
#  2) registers in ExternalFunctionSymbolResolver the usual EABI/libc/libm routines and trims the
#     leading '_' when searching (same criterion as SwiftShader upstream).
# Idempotente.
import sys
from pathlib import Path

T = Path("/home/lineage/android/lineage-17.1")
p = T / "external/swiftshader/src/Reactor/LLVMReactor.cpp"
s = p.read_text(encoding="utf-8", errors="surrogateescape")
if "V80" in s:
    print("LLVMReactor.cpp: already patched"); print("V80_DONE"); sys.exit(0)

edits = [
    ("#include <math.h>\n",
     '''#include <math.h>
#include <string.h>
#include <stdlib.h>

/* V80: log de errores de enlace del JIT + rutinas de runtime para ARM32 */
#if defined(__ANDROID__)
#include <android/log.h>
#define REACTOR_LOGE(...) __android_log_print(ANDROID_LOG_ERROR, "SwiftShader", __VA_ARGS__)
#else
#define REACTOR_LOGE(...)
#endif
#if defined(__arm__)
#define REACTOR_AEABI_FUNCS(X) \\
	X(__aeabi_idiv) X(__aeabi_uidiv) X(__aeabi_idivmod) X(__aeabi_uidivmod) \\
	X(__aeabi_ldivmod) X(__aeabi_uldivmod) \\
	X(__aeabi_l2f) X(__aeabi_ul2f) X(__aeabi_l2d) X(__aeabi_ul2d) \\
	X(__aeabi_f2lz) X(__aeabi_f2ulz) X(__aeabi_d2lz) X(__aeabi_d2ulz) \\
	X(__aeabi_memcpy) X(__aeabi_memcpy4) X(__aeabi_memcpy8) X(__aeabi_memmove) X(__aeabi_memmove4) X(__aeabi_memmove8) \\
	X(__aeabi_memset) X(__aeabi_memset4) X(__aeabi_memset8) X(__aeabi_memclr) X(__aeabi_memclr4) X(__aeabi_memclr8)
#define REACTOR_DECL(f) extern "C" void f();
REACTOR_AEABI_FUNCS(REACTOR_DECL)
#undef REACTOR_DECL
#endif
static void reactor_sync_synchronize() { __sync_synchronize(); }
static void reactor_never_called() { REACTOR_LOGE("Reactor: unwind routine called from JIT code"); abort(); }
'''),
    ('''			func_.emplace("truncf", reinterpret_cast<void*>(truncf));
		}

		void *findSymbol(const std::string &name) const
		{
			FunctionMap::const_iterator it = func_.find(name);
			return (it != func_.end()) ? it->second : nullptr;
		}''',
     '''			func_.emplace("truncf", reinterpret_cast<void*>(truncf));
			/* V80: runtime que LLVM puede invocar desde el codigo JIT (claves sin '_' iniciales) */
#define REACTOR_ADD(f) func_.emplace(trim(#f), reinterpret_cast<void*>(f));
			REACTOR_ADD(memcpy) REACTOR_ADD(memset) REACTOR_ADD(memmove)
			REACTOR_ADD(sinf) REACTOR_ADD(cosf) REACTOR_ADD(tanf) REACTOR_ADD(asinf) REACTOR_ADD(acosf) REACTOR_ADD(atanf)
			REACTOR_ADD(sinhf) REACTOR_ADD(coshf) REACTOR_ADD(tanhf) REACTOR_ADD(asinhf) REACTOR_ADD(acoshf) REACTOR_ADD(atanhf)
			REACTOR_ADD(atan2f) REACTOR_ADD(expf) REACTOR_ADD(logf) REACTOR_ADD(exp2f) REACTOR_ADD(log2f) REACTOR_ADD(powf)
			REACTOR_ADD(fmodf) REACTOR_ADD(sqrtf) REACTOR_ADD(ceilf) REACTOR_ADD(roundf) REACTOR_ADD(rintf) REACTOR_ADD(fabsf)
			REACTOR_ADD(fminf) REACTOR_ADD(fmaxf)
#if defined(__arm__)
			REACTOR_AEABI_FUNCS(REACTOR_ADD)
#endif
#undef REACTOR_ADD
			func_.emplace("sync_synchronize", reinterpret_cast<void*>(reactor_sync_synchronize));
			func_.emplace("aeabi_unwind_cpp_pr0", reinterpret_cast<void*>(reactor_never_called));
			func_.emplace("aeabi_unwind_cpp_pr1", reinterpret_cast<void*>(reactor_never_called));
			func_.emplace("aeabi_unwind_cpp_pr2", reinterpret_cast<void*>(reactor_never_called));
		}

		static const char *trim(const char *name)
		{
			while(name[0] == '_') { name++; }
			return name;
		}

		void *findSymbol(const std::string &name) const
		{
			FunctionMap::const_iterator it = func_.find(trim(name.c_str()));
			return (it != func_.end()) ? it->second : nullptr;
		}'''),
    ('''					return objLayer.findSymbol(name, true);
				},
				[](llvm::Error err) {
					if (err)
					{
						// TODO: Log the symbol resolution errors.
						return;
					}
				})),''',
     '''					llvm::JITSymbol sym = objLayer.findSymbol(name, true);
					if(!sym)   /* V80 */
					{
						REACTOR_LOGE("Reactor: unresolved external symbol '%s'", name.c_str());
					}
					return sym;
				},
				[](llvm::Error err) {
					if (err)
					{
						REACTOR_LOGE("Reactor: symbol resolution error: %s", llvm::toString(std::move(err)).c_str());
						return;
					}
				})),'''),
    ('''			if(!expectAddr)
			{
				return nullptr;
			}''',
     '''			if(!expectAddr)
			{
				REACTOR_LOGE("Reactor: routine link failed: %s", llvm::toString(expectAddr.takeError()).c_str());   /* V80 */
				return nullptr;
			}'''),
]
for old, new in edits:
    if s.count(old) != 1:
        print(f"V80_ERROR: unique block not found: {old[:60]!r}"); sys.exit(1)
    s = s.replace(old, new, 1)
p.write_text(s, encoding="utf-8", errors="surrogateescape")
print("LLVMReactor.cpp: log de enlace + simbolos EABI/libm registrados")
print("V80_DONE")
